### ISSUE TITLE
systemctl mask systemd-rfkill@.service

### ISSUE THREAD

**Issue by Zverushko** [linrunner/TLP#166]
unit name systemd-rfkill@.service is not valid 

fedora 23

how fix that?

thx!

**Comment by dywisor** [comment]
Due to changes in systemd v227, you now need to mask systemd-rfkill.service and its corresponding .socket unit:

```systemctl mask systemd-rfkill.socket systemd-rfkill.service```

refs:
* [release notes item](https://github.com/systemd/systemd/blob/v227/NEWS#L162-L167)
* [commit that introduced this change](https://github.com/systemd/systemd/commit/d35c1bb1f4b90993124f817f6f54a933e3be5f6b)

**Comment by linrunner** [comment]
@dywisor: F23 has systemd v222 afaik. 

@Zverushko: Please provide:

    systemctl list-unit-files | grep rfkill
    rpm -q systemd
    rom -ql systemd

**Comment by linrunner** [comment]
The error message is wrong, the service is masked correctly.

**Comment by linrunner** [comment]
Installation instructions updated.

**Comment by brianpepino** [comment]
I am running Fedora 32 and TLP 1.3.1 and I am still seeing this notice - "Notice: systemd-rfkill.socket is not masked -- invoke "systemctl mask systemd-rfkill.socket" to correct this!"

Any update or guidance? Thank you in advance.
