### ISSUE TITLE
Support custom scripts to set battery thresholds

### ISSUE THREAD

**Issue by DoMiNeLa10** [linrunner/TLP#396]
**Is your feature request related to a problem? Please describe.**

I've upgraded my ThinkPad to coreboot recently, and lost `tp-smapi` support in the process, which effectively disabled the possibility to set battery thresholds via `tlp`. Coreboot provides a tool called `ectool` which can write to the ram of the EC, and it's trivial to figure out where battery thresholds are stored and set them up with single commands. It would be nice to let people write scripts that would handle setting the thresholds (and it could open up the possibility for other laptops to support this feature).

**Describe the solution you'd like**

The easiest solution would be to provide an option to give a script to set (and maybe get) battery thresholds which would receive them as arguments, which for example could look like this:

    $script <set|get> <start|end> [value]

A clear and concise description of:

* Your use case(s)

ThinkPad T420 with coreboot (doesn't work with `tp-smapi`, but `ectool` from coreboot can be used to set battery thresholds). Reading thresholds works as is (seems to use `natacpi`).

* What you want to happen

Be able to give a custom script to set battery thresholds so I don't have to set them outside of `tlp` and be able to run commands like `tlp fullcharge`.

**Describe alternatives you've considered**

Writing own shell scripts to do the same thing.

**Additional context**

Add any other context and references about the feature request here:

* New kernel interfaces: please provide links to the description and usage examples

Not needed.

* Sample shell code

I'm not a bash guru, but I was able to put together this script (getting thresholds isn't implemented as they aren't needed in my case and this is a proof of concept).

    #!/bin/bash
    
    if (( $EUID != 0 )); then
        echo "script must be run as root"
        exit 1
    fi
    
    # path to the ectool binary
    ectool=/home/user/git/coreboot/util/ectool/ectool
    
    # start and end thresholds (in this case for T420)
    start_threshold_address=b0
    end_threshold_address=b1
    
    if [[ "$1" != "set" ]]; then
        echo "only set command supported"
        exit 1
    fi
    
    case "$2" in
        "start")
            address=$start_threshold_address
            ;;
        "end")
            address=$end_threshold_address
            ;;
        *)
            echo "second argument must be either start or end"
            exit 1
    esac
    
    if [ -z "$3" ]; then
        echo "value must be passed"
        exit 1
    fi
    
    if (( "$3" < 0 && "$3" > 100 )); then
        echo "value out of range"
        exit 1
    fi
    
    hexvalue=$(printf "%x" "$3")
    
    "$ectool" -w "$address" -z "$hexvalue"

**Comment by linrunner** [comment]
Hi,

in the short run you're better off implementing and publishing your own tool for the task. Then let it mature with input from users. User base for Coreboot + thresholds should be quite narrow (I don't own such hardware).

I'm not convinced, either, your approach of directly writing the EC is sustainable:

* Regarding the *20 generation: tp-smapi also writes to the EC and fails to operate start_charge_thresh and force_discharge, only stop_charge_thresh actually works – TLP uses tpacpi-bat or natacpi with ACPI calls instead
* Newer generations work with ACPI calls only

An indication that Lenovo has changed basic things.

I saw an effort to implement the very same ACPI calls tpacpi-bat and natacpi use in [Coreboot](https://github.com/teleshoes/tpacpi-bat/issues/83). This would mean thresholds and force_discharge get supported in TLP out-of-the-box. This seems to me to be the most sensible approach. Did you ask there?

I'm not ready to add a 4th "driver" for ThinkPad battery features to TLP. The 3-fold logic caused by the appearance of natacpi is already complicated enough and gave me some headaches. See the [code](https://github.com/linrunner/TLP/blob/master/func.d/35-tlp-func-batt).

Your suggested TLP interface for _custom_ scripts for battery features is unimaginable for me. This would lead to a support nightmare.
