### ISSUE TITLE
Much power used by camera, on battery (on X1CG6)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linrunner/TLP#397]
[x] I've read and accepted the [Bug Reporting Howto](https://github.com/linrunner/TLP/blob/master/.github/Bug_Reporting_Howto.md)

**Describe the bug**

On my X1CG6, the camera uses a lot of power on battery. Here is a [screenshot](https://i.postimg.cc/zGbhRwfr/image.png) that shows that state of affairs.

**Expected behavior**

Perhaps TLP counts the camera as an input device. Still, might tlp be made to reduce the camera's hefty power usage - the large power drain, I mean, when the computer is on battery and (as is the case in stats screenshotted above) not even using the camera?

**To Reproduce**

Steps to reproduce the unexpected behavior:

1. Does the problem occur on battery or AC or both? Battery
2. Actions to reproduce the behaviour. Have X1GC6. Have TLP, set to its defaults. Switch to battery power. Run powertop.
4. **Full output of `tlp-stat` via https://gist.github.com/ for *all* cases of 1**: [here](https://gist.github.com/LinuxOnTheDesktop/932398f53b6caba2912723d9787aaa96).

**Additional context**

Linux Mint 19.1 x64 Cinnamon.
Linux kernel 5.0.0-050000-generic

**Comment by linrunner** [comment]
Hi, I consider this a support question not a bug report. May I suggest that you ask in the Linux forum of your choice? See the FAQ for powertop.

Btw: your output may confuse supporters

* It shows AC although your problem is on battery
* Effective USB settings (control=on) do not match the actual configuration; I can only guess you experimented with the settings and didn't refresh via `tlp start` afterwards
