### ISSUE TITLE
Continuos charging/discharging loop has killed my battery

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [linrunner/TLP#504]
# Bug description
I've used tlp in my MSI Modern for 4 months and the battery capacity went from 100% to 60% and I was able to see the deterioration of 1 or 2% weekly.

# What I've tried
Once I've tried uninstalling tlp, I've seen that the battery doesn't deteriorate as fast as before.

I've recently found two lines in the config file that may fix my problem:
```
START_CHARGE_THRESH_BAT0=
STOP_CHARGE_THRESH_BAT0=
```
If I set both to 100 I keep receiving notification saying "battery is charging", "battery is discharging", "battery is charging" and so on...

# My idea on the solution
I think it's because of the charging and discharging loop that keeps the battery between 95/96% and 100% when AC is plugged in. 
Today's laptops should ignore the battery if completely charged and been powered by the external source (AC) so this loop should be removed.

**Comment by linrunner** [comment]
Hi,

I'm sorry, but TLP is not related to your issue. 

No matter how you configure START/STOP_CHARGE_THRESH_BAT0 (note that these setting are disabled/commented by default), this won't affect the charging behaviour of your laptop because there is no kernel driver for MSI laptops providing charge thresholds for wear control. 

What you observe is controlled by MSI's firmware only and can't be affected by TLP or any other Linux software.

I suggest you ask for help in a MSI or hardware oriented forum. Maybe your BIOS offers a possibility to influence the charging behaviour.
