### ISSUE TITLE
/tmp folder filled with tlp temporay files

### ISSUE THREAD

**Issue by AlecsFerra** [linrunner/TLP#582]
I noticed that leaving my laptop on for some days this software fills the ```/tmp``` directory with temporary files, how can I find the root of the issue?

**Comment by linrunner** [comment]
Generally I expect that people provide actionable information in their issue in order to enable analysis; the issue template should help with this. Which amounts at least to the full output of

    sudo tlp-stat 

As the output is long, via [Gist](https://gist.github.com/) please.

In your case, of course, a listing of the directory in question is also required, e.g.

    ls -l /tmp

**Comment by linrunner** [comment]
Also please show the output of

    sudo tlp start

**Comment by linrunner** [comment]
I am missing your details.

**Comment by AlecsFerra** [comment]
Sorry I was occupied with uni

https://gist.github.com/AlecsFerra/817683ab48a0f364aa9df61450dbd71b

**Comment by linrunner** [comment]
Something or someone calls a part of TLP in user context (alecs). TLP stores the current configuration in /tmp and deletes it after the program ends. 

But the installation package only creates tasks that run with root rights, so these calls here must be set up by yourself.

So what exactly did you do?

**Comment by AlecsFerra** [comment]
Can running tlp-stat without root priviliges run a new instance?

**Comment by AlecsFerra** [comment]
Or changing the mode

**Comment by linrunner** [comment]
The call of tlp-stat creates such a tempfile. Instead of counter-questions, I would now like to have precise information on how and with which parameters you call tlp-stat so that we can find out why the tempfile is not deleted.

**Comment by AlecsFerra** [comment]
I run this command
```exec = sudo tlp-stat -s | grep -q 'Mode           = AC' && echo " " || echo "鈴  "```

**Comment by linrunner** [comment]
Thats strange. tlp-stat `-s` does not require sudo, but if you call it with sudo, it writes the configuration but to **/tmp**, but to **/run/tlp/run.conf**. Is there perhaps another call you have set up?

Instead of scraping tlp-stat's output take a look at `run-on-ac` and `run-on-bat`. They are much leaner and do not read any configuration --> https://linrunner.de/tlp/usage/run-on.html

**Comment by linrunner** [comment]
Any news on this?

**Comment by linrunner** [comment]
I'll close here. Nevertheless, you are welcome to post new findings about your problem here.
