### ISSUE TITLE
Compatibility of TLP with ASUS-specific tools (asusctl, asusd, rog-control) on Arch Linux

### ISSUE THREAD

**Issue by CristianTacoronteRivero** [linrunner/TLP#767]
Is your feature request related to a problem? Please describe.

I am trying to install TLP on my ASUS laptop running Arch Linux, which has dependencies like asusctl, asusd, rog-control, and other ASUS Linux tools. During installation, I encounter conflicts between TLP and these ASUS-specific utilities, specifically with power-profiles-daemon (PPD), which came pre-installed.

I would like to confirm if there is any way to resolve these conflicts without removing ASUS-related tools, as they are essential for managing hardware on ASUS devices.

Describe the solution you'd like

My use case:

I need to manage power efficiency and battery life on my ASUS laptop using TLP, while also maintaining ASUS-specific functionality for things like fan control, RGB, and system profiles.
Ideally, I would like to install TLP alongside ASUS-related tools without requiring the removal of power-profiles-daemon or any ASUS utilities.
Describe alternatives you've considered

Uninstalling power-profiles-daemon, but I am concerned about possible issues with ASUS-specific tools.
Seeking an alternative configuration that allows TLP to coexist with ASUS Linux tools without conflicting with power management functions.
Additional context

References:

Links to ASUS Linux tools and configuration recommendations for ASUS devices on Arch Linux (for example, [ArchWiki ASUS](https://wiki.archlinux.org/title/ASUS_Linux) and asusctl GitHub repo).
Any advice on managing conflicts between TLP and power-profiles-daemon or ASUS Linux tools would be valuable.

**Comment by linrunner** [comment]
I don't see it as a sensible approach to promote the simultaneous use of several power-saving tools that work on the same tunables. This leads to unpredictable results and additional support efforts (this issue is proof of that).

**asusctl** seems to _optionally_ use the power-profiles-daemon to control platform power profiles. TLP can do the same, see the documentation: https://linrunner.de/tlp/faq/ppd.html

If you absolutely want to use TLP and power-profiles-daemon in parallel, please research the technical details yourself.
