### ISSUE TITLE
Abillity to set PL1/PL2 power limits on modern Intel chips

### ISSUE THREAD

**Issue by Tarballwalf** [linrunner/TLP#774]
**Is your feature request related to a problem? Please describe.**

The ability to configure PL1/PL2 power limits should help with laptops that overheat or misbehave and run at wrong values. Many gaming laptops come with proprietary software on Windows that lets you control power limits of the CPU, like ASUS own ROG control center or Lenovo vantage software

**Describe alternatives you've considered**

I have considered using the asus on linux project with their asusctl and rog control center, but it seems to be broken or interfere with TLP in some way?

**Add any other context and references about the feature request here:**
PL1/PL2 power limits should be available on many Intel H and HX chips, I'm not entirely sure about their other SKUs

As for kernel interfaces, the intel-rapl interface could be used. My knowledge is limited, and I will try to provide as much info as I can to help support the implementation of this feature

**Comment by linrunner** [comment]
Hi,

I don't want to include this because it involves too much risk of hardware damage and the determination of the configuration values is not easy enough to explain.

There are already tools that you can use:  https://www.cnx-software.com/2022/09/08/how-to-check-tdp-pl1-and-pl2-power-limits-in-windows-and-linux/
